export const UPDATE_TRADE_RULES_TABLE = 'UPDATE_TRADE_RULES_TABLE';

export const UPDATE_EDIT_RULES_DICT = 'UPDATE_EDIT_RULES_DICT';

export const DELETE_EDIT_RULES_DICT = 'DELETE_EDIT_RULES_DICT';

export const SHOW_TRADAE_GROUP = 'SHOW_TRADAE_GROUP';
export const HIDE_TRADAE_GROUP = 'HIDE_TRADAE_GROUP';

export const SHOW_TRADE_RULE = 'SHOW_TRADE_RULE';
export const HIDE_TRADE_RULE = 'HIDE_TRADE_RULE';

export const SHOW_EDIT_TRADE_RULE = 'SHOW_EDIT_TRADE_RULE';
export const HIDE_EDIT_TRADE_RULE = 'HIDE_EDIT_TRADE_RULE';

// export const DELETE_REMARK_DIALOGS = 'DELETE_REMARK_DIALOGS';