export const UPDATE_TRADE_RULES = 'UPDATE_TRADE_RULES';

// export const UPDATE_REMARK_DIALOGS = 'UPDATE_REMARK_DIALOGS';

// export const DELETE_REMARK_DIALOGS = 'DELETE_REMARK_DIALOGS';

// export const UPDATE_TRADERULE_REMARK = 'UPDATE_TRADERULE_REMARK';

// export const UPDATE_COPY_TO_NEW__GROUP_DIALOGS = 'UPDATE_COPY_TO_NEW__GROUP_DIALOGS';

// export const DELETE_COPY_TO_NEW__GROUP_DIALOGS = 'DELETE_COPY_TO_NEW__GROUP_DIALOGS';

// export const UPDATE_TRADERULE_TABLE = 'UPDATE_TRADERULE_TABLE';

export const UPDATE_EDIT_RULES_DICTS = 'UPDATE_EDIT_RULES_DICTS';

export const DELETE_EDIT_RULES_DICTS = 'DELETE_EDIT_RULES_DICTS';

export const SHOW_TRADAE_GROUP = 'SHOW_TRADAE_GROUP';
export const HIDE_TRADAE_GROUP = 'HIDE_TRADAE_GROUP';

export const SHOW_TRADE_RULE = 'SHOW_TRADE_RULE';
export const HIDE_TRADE_RULE = 'HIDE_TRADE_RULE';

export const SHOW_EDIT_TRADE_RULE = 'SHOW_EDIT_TRADE_RULE';
export const HIDE_EDIT_TRADE_RULE = 'HIDE_EDIT_TRADE_RULE';

// export const DELETE_REMARK_DIALOGS = 'DELETE_REMARK_DIALOGS';