//显示加载
export const SHOW_LOADING = 'SHOW_LOADING';

//关闭加载
export const HIDE_LOADING = 'HIDE_LOADING';



//update_global_context
export const UPDATE_GLOBAL_CONTEXT = 'UPDATE_GLOBAL_CONTEXT';

export const UPDATE_GLOBAL_USER_INFO = 'UPDATE_GLOBAL_USER_INFO';
export const UPDATE_GLOBAL_ROLES = 'UPDATE_GLOBAL_ROLES';
export const UPDATE_GLOBAL_QUOTE_TYPES = 'UPDATE_GLOBAL_QUOTE_TYPES';
export const UPDATE_GLOBAL_SOURCES = 'UPDATE_GLOBAL_SOURCES';
export const UPDATE_GLOBAL_LPS = 'UPDATE_GLOBAL_LPS';
export const UPDATE_GLOBAL_STD_SYMBOLS = 'UPDATE_GLOBAL_STD_SYMBOLS';
//update_global_dialog_zIndex
export const UPDATE_GLOBAL_ZINDEX= 'UPDATE_GLOBAL_ZINDEX';

//update_global_LOCALE
export const UPDATE_GLOBAL_LOCALE= 'UPDATE_GLOBAL_LOCALE';