export const SHOW_ADD_QUOTERULE_TABLE = 'SHOW_ADD_QUOTERULE_TABLE';

export const HIDE_ADD_QUOTERULE_TABLE = 'HIDE_ADD_QUOTERULE_TABLE';

export const SHOW_EDIT_QUOTERULE_TABLE = 'SHOW_EDIT_QUOTERULE_TABLE';

export const HIDE_EDIT_QUOTERULE_TABLE = 'HIDE_EDIT_QUOTERULE_TABLE';