// export const UPDATE_REMARK_DIALOGS = 'UPDATE_REMARK_DIALOGS';

// export const DELETE_REMARK_DIALOGS = 'DELETE_REMARK_DIALOGS';

// export const UPDATE_TRADERULE_REMARK = 'UPDATE_TRADERULE_REMARK';

// export const UPDATE_COPY_TO_NEW__GROUP_DIALOGS = 'UPDATE_COPY_TO_NEW__GROUP_DIALOGS';

// export const DELETE_COPY_TO_NEW__GROUP_DIALOGS = 'DELETE_COPY_TO_NEW__GROUP_DIALOGS';

// export const UPDATE_TRADERULE_TABLE = 'UPDATE_TRADERULE_TABLE';

export const SHOW_MT4_POSITIONS = 'SHOW_MT4_POSITIONS';

export const HIDE_MT4_POSITIONS = 'HIDE_MT4_POSITIONS';

export const UPDATE_MT4_POSITIONS_RESULT = 'UPDATE_MT4_POSITIONS_RESULT';
// export const DELETE_REMARK_DIALOGS = 'DELETE_REMARK_DIALOGS';